[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["CI=false REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL yarn build"]

[start]
cmd = "npx serve -s build -l ${PORT:-3000}"
